# [KDT] ch1 데이타분석용 파이썬 이해

In [1]:
import os
os.getcwd()

'c:\\OneDrive\\문서\\Office\\DS 2022\\DS강의(onedrive)\\강의\\KDT\\2차_230227\\실습'

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
pd.__version__

'1.4.4'

# 1. Numpy

In [4]:
#import numpy 
import numpy as np
import numpy as np

In [5]:
# nd array 1차원
np.array([1,2,3,4,['a']])

array([1, 2, 3, 4, list(['a'])], dtype=object)

In [6]:
# nd array 2차원
np.arange(1,30,2)
np.array([[ 1,  3,  5,  7,  9,11, 13, 15, 17, 19, 21, 23, 25, 27, 29]]).shape

(1, 15)

In [7]:
# nd array 3차원
np.array([[[ 1,  3,  5,  7,  9,11, 13, 15, 17, 19, 21, 23, 25, 27, 29]]]).shape

(1, 1, 15)

### 1_1. ndarray의 데이터 타입

In [8]:
# int type
list1 = [1,2,3]
list1
print(type(list1))
array1 =np.array(list1)
array1
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [9]:
# int type + object
list2 = [1,2,3,4.0,'test']
list2
array2 = np.array(list2)
print(array2, array2.dtype )


# int type + float


['1' '2' '3' '4.0' 'test'] <U32


In [10]:
# type 변환, astype('float'), astype('int')
array_int = np.array([1,2,3])
array_float = np.array([1.5,2.5,3.5])
array_float.dtype

array_int.astype('float').dtype
array_float.dtype

array_float.astype('int')
array_float


array([1.5, 2.5, 3.5])

In [11]:
# np.array([1,2,3,4])
np.array([1,2,3,4,['a']])

array([1, 2, 3, 4, list(['a'])], dtype=object)

In [12]:
######## 12: 00

### 1_2. ndarray를 편리하게 생성하기 - arange, zeros, ones

최신버전 '1.24.2'
강사버전 '1.23.3' 입니다.
'1.24.2'

In [13]:
# np.arange

sequence_array = np.arange(2,10,2)
sequence_array.dtype
sequence_array.shape

(4,)

In [14]:
#(3, 2) shape을 가지는 모든 원소가 0, dtype은 int32 인 ndarray 생성. 
zero_array = np.zeros((3,2))
zero_array
#(3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성.

one_array = np.ones((3,2))
one_array.dtype
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 1_3. ndarray reshape

In [15]:
# reshape
array1 = np.arange(10)
array1

# (2, 5) shape으로 변환
array2 = array1.reshape(2,5)
array2

#(5, 2) shape으로 변환
array3 = array1.reshape(5,2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
# reshape (X)
# array4 = array1.reshape(4,3)
# array4

In [17]:
# reshape(-1)
array2 = array1.reshape(-1,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# reshape (X)
# array2 = array1.reshape(-1,3)
# array2

In [19]:
# reshape (ndarray 차원변환) 
array1 = np.arange(8)
print( 'array1:\n', array1.tolist())
print( 'array1:\n', array1 )

# 1차원 ndarray를 3차원 ndarray로 변환 
array3d = array1.reshape((2,2,2))
print( 'array3d:\n', array3d.tolist())
print( 'array3d:\n', array3d )

# 3차원 ndarray를 2차원 ndarray로 변환하되 칼럼갯수는 1 
array5 = array3d.reshape(-1,1)
print( 'array5:\n', array5.tolist())
print( 'array5:\n', array5 )

# 1차원 ndarray를 2차원 ndarray로 변환화되 칼럼 갯수는 1 

# 3차원 ndarray를 1차원으로 변환 

array1:
 [0, 1, 2, 3, 4, 5, 6, 7]
array1:
 [0 1 2 3 4 5 6 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### 1_4. ndarray indexing

* 단일 값 추출 (1d array)

In [20]:
# 1에서 부터 12 까지의 1차원 ndarray 생성 
arr = np.arange(12)

print('arr=', arr)
arr[2]

arr= [ 0  1  2  3  4  5  6  7  8  9 10 11]


2

In [21]:
# array[-1] 맨 뒤값
arr[-1]

11

단일 값 추출 (2d array)

In [22]:
# 실습 array 생성
arr12 = np.arange(12)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# ndarray indexing
arr26 = arr12.reshape(2,6)
arr26[0,2]
arr26[1,3]
arr26

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

* 슬라이싱 - 연속된 인덱스상의 값을 추출하는 방식

In [24]:
# 실습 array 생성

print('arr12= ', arr12)
arr12[0:3]
arr12[3:]


arr12=  [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# 슬라이싱 1d
print('arr12= ', arr12)
arr12[0:3]
arr12[3:]

arr12=  [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
# 슬라이싱 2d
print('arr26= ', arr26)


arr26[0:2   , 1:3  ]
arr26[:2   , -1  ]

arr26=  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 5, 11])

* 팬시 인덱싱 - 리스트나 ndarray로 인덱스 집합을 지정하는 방식

In [27]:
# 실습 array 생성
arr_12 = np.arange(12)
print('arr_12\n', arr_12)
arr_26 = arr_12.reshape(2,6)
print('arr_26\n', arr_26)
arr_34 = arr_12.reshape(3,-1)
print('arr_34\n', arr_34)

arr_12
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr_26
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr_34
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# 팬시 인덱싱
arr_34[[ 0, 1], 0: 2    ]

array([[0, 1],
       [4, 5]])

* 불린 인덱싱- True, False 조건으로 인덱스 집합을 지정하는 방식

In [29]:
# 실습 array 생성
arr_12 = np.arange(12)
print('arr_12\n', arr_12)

arr_12
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
# 불린 인덱싱
arr12 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [31]:
# 불린 인덱싱, boolean_indexes => boolean_indexes는 필터링에 활용
arr12[ arr12 > 4  ]
arr12[[False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True] ]

array([ 5,  6,  7,  8,  9, 10, 11])

In [32]:
# arr_12를 2로 나눈 나머지가 짝수인가
np.mod(arr12, 2) == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [33]:
# arr_12에서 짝수만 추출(필터링)

boolean_indexer = [True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False]
arr12[boolean_indexer]

array([ 0,  2,  4,  6,  8, 10])

In [34]:
# 수업중 질문, 조건문 2개도 가능한가요?  가능합니다
# arr_12에서 조건문 2개 (필터링 인덱서 생성)
(arr_12 > 2) & (arr_12 < 7) 

array([False, False, False,  True,  True,  True,  True, False, False,
       False, False, False])

In [35]:
# arr_12에서 조건문 2개 (필터링)
arr_12[(arr_12 > 2) & (arr_12 < 7)]

array([3, 4, 5, 6])

In [36]:
#########################14:03

# 14:13분에 시작하겠습니다

# 14:55분에 시작하겠습니다

연습문제 풀이

# 2. Pandas

### 2_1. DataFrames 생성

* pd.DataFrame() 

In [37]:
# list로 생성
import pandas as pd
list = [[1,2,3,4],[5,6,7,8]]
list
pd.DataFrame(list)
# pd.DataFrame([[1,2,3,4],[5,6,7,8]])

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [38]:
# list로 생성, columnlumn 추가
pd.DataFrame(list, columns=['A','B','C','D'])

A  B  C  D
0  1  2  3  4
1  5  6  7  8

In [39]:
# list로 생성, column 추가, indexex 추가
pd.DataFrame(list, columns=['A','B','C','D'], index = ['one', 'two'])

A  B  C  D
one  1  2  3  4
two  5  6  7  8

In [40]:
# array로 생성
arr = np.arange(12)
arr2 = arr.reshape(3,-1)
arr2
pd.DataFrame(data=arr2)

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [41]:
# array로 생성, column추가, index 추가
pd.DataFrame(data=arr2)
pd.DataFrame(data=arr2,  columns=['A','B','C','D'], index = ['one', 'two', 'three'])

A  B   C   D
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [42]:
# 딕셔너리로 생성
dic = {'A' : [1,2,3]       ,'B':[4,5,6], 'C' : [7,8,9]}
dic

{'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}

In [43]:
# 딕셔너리로 생성, index 추가
pd.DataFrame(data=dic, index = ['one', 'two', 'three'] )

A  B  C
one    1  4  7
two    2  5  8
three  3  6  9

* DataFrame을 넘파이 ndarray, list, 딕셔너리로 변환하기

In [44]:
# DataFrame 생성
df = pd.DataFrame(data=dic, index = ['one', 'two', 'three'] )
df

A  B  C
one    1  4  7
two    2  5  8
three  3  6  9

In [45]:
# DataFrame을 딕셔너리로 변환
df.to_dict()

{'A': {'one': 1, 'two': 2, 'three': 3},
 'B': {'one': 4, 'two': 5, 'three': 6},
 'C': {'one': 7, 'two': 8, 'three': 9}}

In [46]:
# DataFrame을 ndarray로 변환
df.values

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int64)

In [47]:
# DataFrame을 list로 변환
df.values.tolist()

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

## Quiz 1

1) 아래 DataFrame을 딕셔너리로 생성하시오

In [48]:
# pd.DataFrame({ })


In [49]:
dic_ex = {'name': ['kdh100', 'kdh101', 'kdh102', 'kdh103'],
         'jumin7': ['990623-2', '900303-2', '681205-2', '931226-2'],
         'sex': ['F', 'F', 'F', 'F']}
pd.DataFrame(dic_ex, index = [0, 1, 2, 3])

name    jumin7 sex
0  kdh100  990623-2   F
1  kdh101  900303-2   F
2  kdh102  681205-2   F
3  kdh103  931226-2   F

### 2_2. Data Frame 읽기
* read_csv()** csv, txt, Excel Data 가능


* 데이터 읽어오기 pd.read_csv('file_name.csv')
- [데이터 읽어오기 참고(csv,txt,xlsx,UTF-8 인코딩)]
- df = pd.read_csv('file_name.csv')
- txt: 텍스트 파일. 특정 구분자로 구분되어있다면 sep 인자에 명시(탭(tab)은 sep='\t', '|' 는 sep='|'
- df = pd.read_csv('file_name.csv', encoding='cp949') - 한글파일 인코딩 에러시
- df = pd.read_csv('file_name.csv', sep='\t') - 구분자: Tab일때
                                        
- xlsx: 엑셀 파일. 특정 시트(sheet)의 데이터만 읽어올 경우 sheet_name 인자에 시트명 또는 순번을 입력해준다.
- df = pd.read_excel('file.xlsx')
- df = pd.read_excel('file.xlsx', sheet_name = 'first_sheet')

In [50]:
import os
os.getcwd()

'c:\\OneDrive\\문서\\Office\\DS 2022\\DS강의(onedrive)\\강의\\KDT\\2차_230227\\실습'

In [51]:
# 파일 로딩 (hk_221206.csv), 절대경로/상대경로 (.\\, ..\\)
df_hk = pd.read_csv('.\\data\\hk_221206.csv') # df_hk 라는 dataFrame명을 생성

In [52]:
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

In [53]:
df_hk.head(2)

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  
0         1975  
1         2970

**head()와 tail()**

head()는 맨 앞부터 데이터 추출 (기본5개),    
tail()은 맨 뒤부터 데이터 추출 (기본5개)  

In [54]:
df_hk.head(2)

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  
0         1975  
1         2970

**DataFrame 출력 시 option**
* max_rows, max_columns, max_colwidth 설정


In [55]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_colwidth', 1000)
df_hk
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', 50)
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

## Quiz 2

1) bike.csv를 읽고 column이 몇 개 인지 기술 하시오

2) iris.cvs를 읽고 row가 몇 개 인지 기술 하시오 

3) Online2.txt를 읽고 3번째 column이 무엇인지 기술 하시오 

In [56]:
df_bike = pd.read_csv('.\\data\\bike.csv')
df_iris = pd.read_csv('.\\data\\iris.csv')
df_Online2 = pd.read_csv('.\\data\\Online2.txt', sep = '\t' )
df_Online2

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

       InvoiceDate  UnitPrice  CustomerID         Country  
0       2010-12-01       2.55     17850.0  United Kingdom  
1       2010-12-01       3.39     17850.0  United Kingdom  
2       2010-12-01       2.75     17850.0  United Kingdom  
3       2010-12-01       3.39     17850.0  United Kingdom  
4       2010-12-01       3.39     17850.0  United Kingdom  
...            ...        ...         ...             ...  
541904  2011-12-09       0.85     12680.0          France  
541905  2011-12-09       2.10     12680.0          France  
541906  2011-12-09       4.15     12680.0          France  
541907  2011-12-09       4.15     12680.0          France  
541908  2011-12-09       4.95     12680.0          France  

[541909 rows x 8 columns]

### 2_3. DataFrame 속성(attribute)
* df.ndim: 객체의 차원
* df.shape: 각 차원의 길이
* df.dtypes: 데이터 타입 dtype와 구별, 복수형이라야 함
* df.info(): 데이터 타입 정보 요약, 결측치 정보
* df.columns: column명
* df.describe(): 수치형 데이터 요약 정보

In [57]:
# df.ndim: 객체의 차원
df_hk.ndim

2

In [58]:
# df.shape: 각 차원의 길이
df_hk.shape

(250, 10)

In [59]:
# df.dtypes: 데이터 타입 dtype와 구별, 복수형이라야 함
df_hk.dtypes

name            object
jumin7          object
gender          object
height         float64
age              int64
blood_type      object
company         object
grades          object
salary           int64
expenditure      int64
dtype: object

In [60]:
# df.info(): 데이터 타입 정보 요약, 결측치 정보
df_hk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         250 non-null    object 
 1   jumin7       250 non-null    object 
 2   gender       250 non-null    object 
 3   height       250 non-null    float64
 4   age          250 non-null    int64  
 5   blood_type   250 non-null    object 
 6   company      250 non-null    object 
 7   grades       250 non-null    object 
 8   salary       250 non-null    int64  
 9   expenditure  250 non-null    int64  
dtypes: float64(1), int64(3), object(6)
memory usage: 19.7+ KB


In [61]:
# df.columns: column명
df_hk.columns

Index(['name', 'jumin7', 'gender', 'height', 'age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure'],
      dtype='object')

In [62]:
# df.describe(): 수치형 데이터 요약 정보
df_hk.describe()

height         age        salary   expenditure
count  250.000000  250.000000    250.000000    250.000000
mean   169.569200   39.240000   6357.480000   4971.480000
std     12.283857    8.653899   1849.791383   1861.112508
min    148.100000   20.000000   3080.000000   1330.000000
25%    159.300000   33.000000   5002.500000   3593.750000
50%    168.750000   39.000000   6100.000000   4762.500000
75%    180.375000   46.000000   7427.500000   6272.500000
max    191.800000   55.000000  11990.000000  10865.000000

In [63]:
# df.describe(): all 데이터 요약 정보
df_hk.describe(include='all')

name    jumin7 gender      height         age blood_type company  \
count    250       250    250  250.000000  250.000000        250     250   
unique   250       240      2         NaN         NaN          4       3   
top     hkd1  890419-1      M         NaN         NaN          A       A   
freq       1         3    138         NaN         NaN         84     100   
mean     NaN       NaN    NaN  169.569200   39.240000        NaN     NaN   
std      NaN       NaN    NaN   12.283857    8.653899        NaN     NaN   
min      NaN       NaN    NaN  148.100000   20.000000        NaN     NaN   
25%      NaN       NaN    NaN  159.300000   33.000000        NaN     NaN   
50%      NaN       NaN    NaN  168.750000   39.000000        NaN     NaN   
75%      NaN       NaN    NaN  180.375000   46.000000        NaN     NaN   
max      NaN       NaN    NaN  191.800000   55.000000        NaN     NaN   

       grades        salary   expenditure  
count     250    250.000000    250.000000  
unique      5           NaN           NaN  
top         B           NaN           NaN  
freq      116           NaN           NaN  
mean      NaN   6357.480000   4971.480000  
std       NaN   1849.791383   1861.112508  
min       NaN   3080.000000   1330.000000  
25%       NaN   5002.500000   3593.750000  
50%       NaN   6100.000000   4762.500000  
75%       NaN   7427.500000   6272.500000  
max       NaN  11990.000000  10865.000000

# 16:15분에 시작합니다

### 2_4. Index와 Column 객체

In [64]:
# 파일 로딩 
df_hk = pd.read_csv('.\\data\\hk_221206.csv')
df_hk.head(5)
df_hk[:5]

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   

   expenditure  
0         1975  
1         2970  
2         5905  
3         2935  
4         4015

In [65]:
# Index, column 보기


In [66]:
# Index 객체 추출
df_hk.index

RangeIndex(start=0, stop=250, step=1)

In [67]:
# Index 객체 추출 (전체)
df_hk.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [68]:
# Index 객체 추출 (일부)
df_hk.index.values[:50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [69]:
# column 객체 추출
df_hk.columns

Index(['name', 'jumin7', 'gender', 'height', 'age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure'],
      dtype='object')

In [70]:
# column 객체 추출 (일부)
df_hk.columns[2:5]

Index(['gender', 'height', 'age'], dtype='object')

In [71]:
# column 내용 추출 (1개)
df_hk['age']
df_hk.age

0      22
1      31
2      55
3      28
4      29
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 250, dtype: int64

In [72]:
# column 내용 추출 (2개 이상)
df_hk[['age','jumin7','company']]
# type(df_hk[['age','jumin7']])

age    jumin7 company
0     22  990623-2       A
1     31  900303-2       A
2     55  681205-2       A
3     28  931226-2       B
4     29  920123-1       B
..   ...       ...     ...
245   50  730710-2       A
246   51  720805-2       A
247   52  710929-1       A
248   53  701024-1       A
249   54  691115-2       A

[250 rows x 3 columns]

## Quiz 3

1) bike.csv의 column을 전부 기술 하시오

2) iris.cvs의 정수형 변수는 몇 개 인지 기술 하시오

In [73]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [74]:
df_bike.columns

Index(['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp',
       'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count'],
      dtype='object')

### 2_5. 함수 및 메소드
* df['age'].mean(): 평균값
* df['age'].median(): 중앙값
* df['age'].min(): 최소값
* df['age'].max(): 최대값
* df['age'].var(): 분산
* df['age'].std(): 표준편차
* df['age'].skew(): 왜도
* df['age'].kurt(): 첨도
* df['age'].count(): 개체수
* df['age'].quantile(q = 0.25) : 1사분위수

In [75]:
# 수치형변수 함수 및 메소드
print( "df_hk['age'].min() : ", df_hk['age'].min())
print( "df_hk['age'].max() : ", df_hk['age'].max())
print( "df_hk['age'].var() : ", df_hk['age'].var())
print( "df_hk['age'].std() : ", df_hk['age'].std())
print( "df_hk['age'].skew() : ", df_hk['age'].skew())
print( "df_hk['age'].kurt() : ", df_hk['age'].kurt())

df_hk['age'].min() :  20
df_hk['age'].max() :  55
df_hk['age'].var() :  74.88995983935737
df_hk['age'].std() :  8.653898534149645
df_hk['age'].skew() :  -0.07707060633056183
df_hk['age'].kurt() :  -0.7894949277134797


* df['blood_type'].nunique(): Column내 개별 데이터값 갯수
* df['blood_type'].unique(): Column내 개별 데이터값 내용
* df['blood_type'].value_counts(): Column내 개별 데이터값의 분포

  주의) default는 Null 값 제외, Null값 포함하려면 dropna를 True로 세팅

In [76]:
# 명목형변수 함수 및 메소드
df_hk['blood_type'].nunique()
df_hk['blood_type'].unique()
df_hk['blood_type'].value_counts()

A     84
O     83
B     54
AB    29
Name: blood_type, dtype: int64

## Quiz 4

1) iris.cvs의 column('species')의 value_counts()를 구하시오

2) Online2.txt의 column('Country')의 unique()를 구하시오

In [77]:
print(df_Online2['Country'].nunique())

38


### 2_6. column 생성, 수정, 삭제


In [78]:
# column 생성
df_hk[:2]
df_hk['point'] = 0
df_hk.head(3)

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   

   expenditure  point  
0         1975      0  
1         2970      0  
2         5905      0

In [79]:
df_hk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         250 non-null    object 
 1   jumin7       250 non-null    object 
 2   gender       250 non-null    object 
 3   height       250 non-null    float64
 4   age          250 non-null    int64  
 5   blood_type   250 non-null    object 
 6   company      250 non-null    object 
 7   grades       250 non-null    object 
 8   salary       250 non-null    int64  
 9   expenditure  250 non-null    int64  
 10  point        250 non-null    int64  
dtypes: float64(1), int64(4), object(6)
memory usage: 21.6+ KB


In [80]:
# column 수정
df_hk['point'] = df_hk['age'] + 10
df_hk[:2]

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  point  
0         1975     32  
1         2970     41

In [81]:
df_hk['point'] = df_hk['age'] + df_hk['salary']/100
df_hk[:2]

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  point  
0         1975   63.0  
1         2970   78.2

**axis에 따른 삭제**

axis=1 일 경우 drop()은 column 방향으로 삭제

In [82]:
# 1개 column 삭제
df_hk.drop('point', axis = 1, inplace=True)
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

# 17:10분에 시작하겠습니다

In [83]:
# 2개 이상 column 삭제는 list로 입력. inplace=True일 경우 호출을 한 DataFrame에 drop결과가 직접 반영 
df_drop = df_hk.drop(['age', 'height','salary'], axis=1)
df_drop

name    jumin7 gender blood_type company grades  expenditure
0      hkd1  990623-2      F          A       A      A         1975
1     hkd10  900303-2      F          A       A      B         2970
2    hkd100  681205-2      F          A       A      B         5905
3    hkd101  931226-2      F         AB       B      B         2935
4    hkd102  920123-1      M          O       B      F         4015
..      ...       ...    ...        ...     ...    ...          ...
245   hkd95  730710-2      F          A       A      A         4865
246   hkd96  720805-2      F          O       A      A         4985
247   hkd97  710929-1      M          A       A      B         6625
248   hkd98  701024-1      M          O       A      B         7385
249   hkd99  691115-2      F          B       A      B         6095

[250 rows x 7 columns]

axis=0 일 경우 drop()은 row 방향으로 삭제 

In [84]:
# 1개 row 삭제
df_drop.drop(0, axis=0)

name    jumin7 gender blood_type company grades  expenditure
1     hkd10  900303-2      F          A       A      B         2970
2    hkd100  681205-2      F          A       A      B         5905
3    hkd101  931226-2      F         AB       B      B         2935
4    hkd102  920123-1      M          O       B      F         4015
5    hkd103  910215-2      F          A       B      A         1915
..      ...       ...    ...        ...     ...    ...          ...
245   hkd95  730710-2      F          A       A      A         4865
246   hkd96  720805-2      F          O       A      A         4985
247   hkd97  710929-1      M          A       A      B         6625
248   hkd98  701024-1      M          O       A      B         7385
249   hkd99  691115-2      F          B       A      B         6095

[249 rows x 7 columns]

In [85]:
# 2개 이상 row 삭제
df_drop.drop([0,1,2,3], axis=0)

name    jumin7 gender blood_type company grades  expenditure
4    hkd102  920123-1      M          O       B      F         4015
5    hkd103  910215-2      F          A       B      A         1915
6    hkd104  990623-1      M          A       B      A         2375
7    hkd105  980717-2      F          B       B      B         1330
8    hkd106  970818-1      M         AB       B      C         2360
..      ...       ...    ...        ...     ...    ...          ...
245   hkd95  730710-2      F          A       A      A         4865
246   hkd96  720805-2      F          O       A      A         4985
247   hkd97  710929-1      M          A       A      B         6625
248   hkd98  701024-1      M          O       A      B         7385
249   hkd99  691115-2      F          B       A      B         6095

[246 rows x 7 columns]

column명 변경

In [86]:
# rename
df_hk.rename(columns= {'gender' : 'sex'})

name    jumin7 sex  height  age blood_type company grades  salary  \
0      hkd1  990623-2   F   161.9   22          A       A      A    4100   
1     hkd10  900303-2   F   169.4   31          A       A      B    4720   
2    hkd100  681205-2   F   168.3   55          A       A      B    7280   
3    hkd101  931226-2   F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1   M   188.6   29          O       B      F    4390   
..      ...       ...  ..     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2   F   157.8   50          A       A      A    6990   
246   hkd96  720805-2   F   150.4   51          O       A      A    7110   
247   hkd97  710929-1   M   172.4   52          A       A      B    8000   
248   hkd98  701024-1   M   166.7   53          O       A      B    8760   
249   hkd99  691115-2   F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

In [87]:
df_hk.columns = ['name', 'jumin7', 'gender', 'height', 'age_age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure']
df_hk

name    jumin7 gender  height  age_age blood_type company grades  \
0      hkd1  990623-2      F   161.9       22          A       A      A   
1     hkd10  900303-2      F   169.4       31          A       A      B   
2    hkd100  681205-2      F   168.3       55          A       A      B   
3    hkd101  931226-2      F   155.3       28         AB       B      B   
4    hkd102  920123-1      M   188.6       29          O       B      F   
..      ...       ...    ...     ...      ...        ...     ...    ...   
245   hkd95  730710-2      F   157.8       50          A       A      A   
246   hkd96  720805-2      F   150.4       51          O       A      A   
247   hkd97  710929-1      M   172.4       52          A       A      B   
248   hkd98  701024-1      M   166.7       53          O       A      B   
249   hkd99  691115-2      F   152.6       54          B       A      B   

     salary  expenditure  
0      4100         1975  
1      4720         2970  
2      7280         5905  
3      4060         2935  
4      4390         4015  
..      ...          ...  
245    6990         4865  
246    7110         4985  
247    8000         6625  
248    8760         7385  
249    7470         6095  

[250 rows x 10 columns]

## Quiz 5

1) iris.csv의 column('sepal_length' , 'sepal_width')의 숫자 합을  파생변수 'sepal'로 생성하시오

In [88]:
df_iris[['sepal_length' , 'sepal_width']]

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [89]:
df_iris['sepal'] = df_iris['sepal_length']+df_iris['sepal_width']
df_iris

sepal_length  sepal_width  petal_length  petal_width    species  sepal
0             5.1          3.5           1.4          0.2     setosa    8.6
1             4.9          3.0           1.4          0.2     setosa    7.9
2             4.7          3.2           1.3          0.2     setosa    7.9
3             4.6          3.1           1.5          0.2     setosa    7.7
4             5.0          3.6           1.4          0.2     setosa    8.6
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica    9.7
146           6.3          2.5           5.0          1.9  virginica    8.8
147           6.5          3.0           5.2          2.0  virginica    9.5
148           6.2          3.4           5.4          2.3  virginica    9.6
149           5.9          3.0           5.1          1.8  virginica    8.9

[150 rows x 6 columns]

### 2_7. 인덱싱 및 필터링

* DataFrame [ ] 로 row와 column을 인덱싱

In [90]:
# 파일 로딩 
df_hk = pd.read_csv('.\\data\\hk_221206.csv')
df_hk[:2]

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  
0         1975  
1         2970

In [91]:
# []에 한개의 column만 입력하면 Series 객체를 반환  
df_hk['age']

0      22
1      31
2      55
3      28
4      29
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 250, dtype: int64

In [92]:
# []에 여러개 column을 list로 입력하면 column들로 구성된 DataFrame을 반환  
df_hk[['age','jumin7']]

age    jumin7
0     22  990623-2
1     31  900303-2
2     55  681205-2
3     28  931226-2
4     29  920123-1
..   ...       ...
245   50  730710-2
246   51  720805-2
247   52  710929-1
248   53  701024-1
249   54  691115-2

[250 rows x 2 columns]

In [93]:
# []에 한개 index 정보를 입력하면 DataFrame을 반환  
df_hk[:9]

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   
5  hkd103  910215-2      F   150.2   30          A       B      A    3290   
6  hkd104  990623-1      M   176.0   22          A       B      A    3750   
7  hkd105  980717-2      F   163.4   23          B       B      B    3080   
8  hkd106  970818-1      M   186.3   24         AB       B      C    3110   

   expenditure  
0         1975  
1         2970  
2         5905  
3         2935  
4         4015  
5         1915  
6         2375  
7         1330  
8         2360

In [94]:
# []에 한개 index 정보를 입력하면 DataFrame을 반환  


In [95]:
# []에 index 정보입력 오류
# df_hk[3]

* iloc[ ] integer location : 위치기반 indexing

   [row정보, column정보] row, column 정보는 integer

In [96]:
# iloc
df_hk.iloc[0:3  , 0:5 ]

name    jumin7 gender  height  age
0    hkd1  990623-2      F   161.9   22
1   hkd10  900303-2      F   169.4   31
2  hkd100  681205-2      F   168.3   55

In [97]:
df_hk.iloc[ [0,3,5,7] , [3,5,7]]

height blood_type grades
0   161.9          A      A
3   155.3         AB      B
5   150.2          A      A
7   163.4          B      B

* loc[ ] location : 명칭기반 indexing (slice indexing)

   [row정보, column정보] column 정보는 column명

In [98]:
# loc
df_hk.loc[0:3, 'name' : 'age'  ]

name    jumin7 gender  height  age
0    hkd1  990623-2      F   161.9   22
1   hkd10  900303-2      F   169.4   31
2  hkd100  681205-2      F   168.3   55
3  hkd101  931226-2      F   155.3   28

In [99]:
df_hk['age'] > 30

0      False
1       True
2       True
3      False
4      False
       ...  
245     True
246     True
247     True
248     True
249     True
Name: age, Length: 250, dtype: bool

In [100]:
df_hk.loc[df_hk['age'] > 30, 'age' ]

1      31
2      55
12     32
16     31
17     32
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 205, dtype: int64

* boolean indexing

In [101]:
df_hk.loc[df_hk['age'] > 30, 'age' ]

1      31
2      55
12     32
16     31
17     32
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 205, dtype: int64

## Quiz 6

1) iris.cvs의 column('petal_width') 값이 1.0보다 큰 것은 몇개인지 구하시오

2) bike.cvs의 column dtype이 'int64' 인것만 추출하고 DataFrame명을 'df_bike_int64'로 저장 하시오 

In [102]:
(df_iris['petal_width'] > 1.0).sum()

93

In [103]:
[1,2,3,4,7,9,10,11]

[1, 2, 3, 4, 7, 9, 10, 11]

In [104]:
df_bike_int64 = df_bike.iloc[:, [1,2,3,4,7,9,10,11]]
df_bike_int64

season  holiday  workingday  weather  humidity  casual  registered  \
0           1        0           0        1        81       3          13   
1           1        0           0        1        80       8          32   
2           1        0           0        1        80       5          27   
3           1        0           0        1        75       3          10   
4           1        0           0        1        75       0           1   
...       ...      ...         ...      ...       ...     ...         ...   
10881       4        0           1        1        50       7         329   
10882       4        0           1        1        57      10         231   
10883       4        0           1        1        61       4         164   
10884       4        0           1        1        61      12         117   
10885       4        0           1        1        66       4          84   

       count  
0         16  
1         40  
2         32  
3         13  
4          1  
...      ...  
10881    336  
10882    241  
10883    168  
10884    129  
10885     88  

[10886 rows x 8 columns]

In [105]:
df_bike_int64 = df_bike.loc[:,df_bike.dtypes == 'int64']
df_bike_int64

season  holiday  workingday  weather  humidity  casual  registered  \
0           1        0           0        1        81       3          13   
1           1        0           0        1        80       8          32   
2           1        0           0        1        80       5          27   
3           1        0           0        1        75       3          10   
4           1        0           0        1        75       0           1   
...       ...      ...         ...      ...       ...     ...         ...   
10881       4        0           1        1        50       7         329   
10882       4        0           1        1        57      10         231   
10883       4        0           1        1        61       4         164   
10884       4        0           1        1        61      12         117   
10885       4        0           1        1        66       4          84   

       count  
0         16  
1         40  
2         32  
3         13  
4          1  
...      ...  
10881    336  
10882    241  
10883    168  
10884    129  
10885     88  

[10886 rows x 8 columns]

In [106]:
df_bike.dtypes == 'int64'

datetime      False
season         True
holiday        True
workingday     True
weather        True
temp          False
atemp         False
humidity       True
windspeed     False
casual         True
registered     True
count          True
dtype: bool

## Quiz 7

(실습문제 유형1을 사용하여, : indian_food2.csv (구분자: 쉼표(,), 255 행, 10 컬럼)

1) 단계 1-1. 지역(state) 컬럼을 제거하시오.

2) 단계 1-2. 조리 시간(cook_time)과 재료 준비 시간(prep_time)이 양수(>0)인 데이터만 추출하시오.

# 2/27일 수업 여기까지

### 2_8. 결손 데이터 처리하기
* isna(), dropna(), fillna()

In [107]:
# 파일 로딩 (hk_221206_na.csv)


In [108]:
# isna()


In [109]:
# dropna()


In [110]:
# fillna()


## Quiz 8

(실습문제 유형5을 사용하여, : phone.csv (구분자:  “,” , 105,828 Rows, 10 Columns)

1) 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS이고 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출

### 2_9. sort, aggregation함수, groupby 

* sort_values()


In [111]:
# 파일 로딩


In [112]:
# sort_values, 1개 column 정렬

In [113]:
# n개 column 정렬  ['blood_type', 'age']


In [114]:
# n개 column 정렬, ascending(True/False) 적용


* aggregation (집계함수)

In [115]:
# 1개 column 에 대한 aggregation


In [116]:
# n개 column 에 대한 aggregation


In [117]:
# n개 column 에 대한 n개 aggregation


In [118]:
# n개 column 에 대한 column별 aggregation (dict형태로 입력)


In [119]:
# 1개 column에 2개 이상 aggregation을 적용하면 마지막 aggregation이 적용


In [120]:
# 1개 column에 2개 이상 aggregation 적용 방법


* groupby()

In [121]:
# 1개 column 에 대한 groupby


In [122]:
# n개 column 에 대한 groupby 


* groupby() + aggregation

In [123]:
# groupby


In [124]:
# n개 groupby + n개 aggregation(1개 column)


In [125]:
# n개 groupby + n개 aggregation(column별 동일 aggregation)


In [126]:
# n개 groupby + n개 aggregation(column별 다른 aggregation)


## Quiz 9

1) iris.cvs의 column('species')별로 'sepal_length' , 'sepal_width')의 평균, 중앙값, 최대값을 구하시오

### 2_10. DataFrame의 병합 (join)
* concat

In [127]:
# 파일 로딩


In [128]:
# concat 실습 파일 생성


In [129]:
# concat (row), axis = 0 default 


In [130]:
# concat (column)  axis = 1


* merge

In [131]:
# merge 실습 파일 생성


In [132]:
# merge  (inner join default)


In [133]:
# merge   (left join)


In [134]:
# merge   (outer join)


### 2_11. column내 값 변경
* replace
* map

In [135]:
# 파일로딩

In [136]:
# replace (1개 값 변경)


In [137]:
# replace (n개 값 변경)


In [138]:
# map (n개 값 변경)


### 2_12. apply lambda 식으로 데이터 가공

In [139]:
# 파일 로딩 


In [140]:
# apply lambda


### 2_13. 값 등급화, 분류
* np.where
* cut

In [141]:
# np.where 2개
# np.where(조건, True, False)


In [142]:
# np.where 3개
# np.where(조건1, True, False)
# np.where(조건1, True, 
#                 np.where(조건2, True, False)


In [143]:
# cut
pd.cut(x = df_hk['age'], bins = [0,20,30,40,100], labels = ['10대', '20대', '30대', '40대이상'])

0        20대
1        30대
2      40대이상
3        20대
4        20대
       ...  
245    40대이상
246    40대이상
247    40대이상
248    40대이상
249    40대이상
Name: age, Length: 250, dtype: category
Categories (4, object): ['10대' < '20대' < '30대' < '40대이상']

### 2_14. 날짜 변수 처리 (datetime)

In [144]:
import datetime

In [145]:
# pd.to_datetime


In [146]:
# astype('datetime64')


In [147]:
# datetime.datetime.strptime
df_hk['jumin7'].apply(lambda x : x[0:6]).apply(lambda x : datetime.datetime.strptime(x, '%y%m%d'))

0     1999-06-23
1     1990-03-03
2     2068-12-05
3     1993-12-26
4     1992-01-23
         ...    
245   1973-07-10
246   1972-08-05
247   1971-09-29
248   1970-10-24
249   1969-11-15
Name: jumin7, Length: 250, dtype: datetime64[ns]

In [148]:
# datetime 활용


Quiz 7 (실습문제 유형5을 사용하여, : phone.csv (구분자: “,” , 105,828 Rows, 10 Columns)

1) 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS이고 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출

In [149]:
# 파일 로딩


In [150]:
# 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS


In [151]:
# 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출
